algoritmo "Creuza3"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

  F, C : Real

inicio

    escreva ("Qual é a temperatura aqui ? ")
    leia (F)
    escreval(F)
    C <- (F - 32) / 1.8
    escreva ("A temperatura no Brasil seria " , C:4:1)

fimalgoritmo