algoritmo "Creuza2"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

  Reais, Dolares : Real

inicio
    escreva ("Quantos reais eu tenho? R$")
    Leia (Reais)
    escreval (Reais)
    Dolares <- ( Reais / 4.99)
    escreva ("Posso ter em doláres o valor de US$" , dolares)

fimalgoritmo