algoritmo "Creuza4"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

  valor , impostos : real

inicio

    escreva (" Qual valor do produto? ")
    leia(valor)
    escreval (valor)
    impostos <- (valor * 60) / 100
    escreva ("O valor do impostos será " , impostos)

fimalgoritmo